# Generated by Django 3.0.6 on 2020-08-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='food',
        ),
    ]
